class_name Constants

enum ObjectType {
	NONE,
	PLAYER_BULLET,
	PLAYER_BULLET_SNIPER,
	PLAYER_BULLET_SHOTGUN,
	BULLET_IMPACT,
	ENEMY_HIT_ARMOR,
	ENEMY_HIT_CORE,
	ENEMY_DEATH,
	DASH_PARTICLES
}

const PLAYER_GROUP: String = "Player"
